fedspendingtransparency/openbeta

_concepts/search-results.md

This commit contains a new axure link.

Added axure link to Search Results page

---

_concepts/search-results.md
_layouts/concept.html
_sass/scss/_base.scss
_sass/scss/_concepts.scss
_sass/scss/_navigation.scss

Added the following to this commit:
- Styled the Axure link for Topic pages
- Refactored the topic page code to accommodate
- Replaced a couple of instances of a previous green hex code colour

Created classes for Axure links on Topic pages

---

_concepts/home-page
_concepts/home-page.md

- Also added missing fields for pages with no tabs.

Changed Home Page file format to Markdown

---

_data/home.yml

Updated the content to remove the reference to "three options."

Content for the Contract Award Summary

---

_concepts/archived-search-functionality.md

Added Advanced Data Search, Search Builder, and SQL Search to this archived page.

Archived Search Functionality

---

_concepts/financial-assistance-award-summary.md

The "Headline" text read "Fifnancial".  Updated the spelling to read "Financial"

Fix Spelling of "Headline" Text

---

_concepts/browse.md

Added content, image, and axure link.

Browse the Data

---

_data/home.yml

Fixed Contract Award Summary 
Removed Search Functionality
Added Agency Summary and Financial Assistance Award Summary

Content Updates

---

_concepts/browse.md

Corrected a typo in second sentence

Browse fix

---

_concepts/agency-summary.md

Fixed typo "ideas" and added "Mission statement"

Award Summary Fixes

---

_data/home.yml

Re-ordered to put Agency Summary and Financial Assistance Award Summary after Search Results. 
Contract Award Summary to the end.

Home Page Carousel

---

_concepts/program-summary.md

Updated page with image and axure links.

CFDA Program Summary

---

_concepts/data-download.md

Data Download

---

_data/concepts-landing-page.yml

Concepts Landing Page Update

---

_concepts/data-download.md

Added this page. 
Need axure link and image.

Date Download page

---

_data/concepts-landing-page.yml

Added CFDA Program Summary to Summary section and Download to the General section. 
Still need to verify links to each.

Added to Summary and General concepts

---

_data/home.yml

Added the CFDA Program Summary and the Download the Data.
Removed the Agency Summary and the Home Page.
Still need images

Update to Carousel

---

_data/home.yml

Added Data Download and CFDA Program Summary.
Removed Home Page and Agency Summary

Updated Carousel

---

_concepts/program-summary.md

Had to fix the link to the axsure page

Program Summary

---

_concepts/appropriation-account-summary
_concepts/appropriation-account-summary.md

Still need static image and axure link.

Create Appropriation Account Summary page

---

_data/concepts-landing-page.yml

Added the Developer Tools section and the API

Concepts-landing-page-api

---

_config.yml

Updated the google_analytics_id  to be the "proper" ID per Alice's Account

Updated google_analytics_id to New ID

---

_data/home.yml

Added the API to the carousel and removed Recipient Summary.

API Update

---

_concepts/api.md
_layouts/concept.html
_sass/scss/_concepts.scss
_sass/scss/_layout.scss
css/main.scss

so that users do not have to read across the whole length of the page

Move the right navigation bar to top of page on concepts pages

---

_data/home.yml
_includes/footer.html

Updating the "1-on-1" button to read "One-on-One"

Update 1 on 1 button

---

_data/home.yml

Added new content at the top of the page.
Change "Comment on Proposed Enhancements" to Comment on Proposed Features

Updated Home Page content

---

_concepts/search-results.md

I've updated the content on the Search Results page

Updated Search Results page

---

_data/home.yml

Updated the Contract Award Summary to Contract Summary and Financial Assistance Summary to Grant Summary.

Updated headers

---

_concepts/archived-contract-award-summary.md

Archived V2 of the Contract Award Summary page.

Archived-contract-summary

---

_concepts/contract-award-summary.md

Update Contract Summary

---

_concepts/archived-financial-award-summary

Archived V0.1 of the Financial Assistance Award Summary.

archived-financial-assistance-award-summary

---

_concepts/financial-assistance-award-summary.md

Added new image and link to axure

Update Grant Summary
